### ISSUE TITLE
chrome plugin: not working properly

### ISSUE THREAD

**Issue by linsharon** [linsharon/citasion#3]
i installed the citasion plugin to my chrome.
i clicked the citasion button to add it to my existing project on citasion. 
i went to my project's "references" page and found nothing synchronized there. 
i refreshed the google scholar page, and the added record has the "+" button on display again, instead of showing it is already saved by me before.
![image](https://user-images.githubusercontent.com/785549/164383540-6846a06e-aaa0-430e-92f2-5c1210eac158.png)

**Comment by Neo-Hao** [comment]
Can you try this again? GS entries may take some time to be loaded. When loaded, a check sign would show up instead. That would indicate that the entry has been added to your project.

**Comment by linsharon** [comment]
it works today.
